# RWA Yield Optimizer GUI Docker Compose Configuration
version: '3.8'

services:
  rwa-gui:
    build:
      context: .
      dockerfile: Dockerfile.gui
    container_name: rwa-yield-optimizer-gui
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    volumes:
      - ./data:/app/data
      - gui_data:/app/data
    ports:
      - "8501:8501"
    restart: unless-stopped
    networks:
      - rwa-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Redis for caching (future enhancement)
  redis:
    image: redis:7-alpine
    container_name: rwa-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - rwa-network
    profiles:
      - with-redis

networks:
  rwa-network:
    driver: bridge

volumes:
  gui_data:
  redis_data: